# Generated by Django 3.2.8 on 2021-12-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('usn', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'StudentDetails',
                'verbose_name_plural': 'StudentDetailss',
            },
        ),
    ]
